#!/usr/bin/env bash
docker-compose pull
docker-compose build
docker-compose up -d postgres
until pg_isready --host "$(docker-machine ip dev)"; do sleep 1; done
docker run --rm -ti --link openstack_postgres_1:postgres openstack_mistral-api mistral-db-manage --config-file /etc/mistral.conf upgrade head
docker run --rm -ti --link openstack_postgres_1:postgres openstack_mistral-api mistral-db-manage --config-file /etc/mistral.conf populate
docker run --rm -ti --link openstack_postgres_1:postgres openstack_keystone keystone-manage db_sync
docker-compose up -d
until nc -vz "$(docker-machine ip dev)" 35357; do sleep 1; done
source <(./auth.sh keystone)
bash initial.sh
source <(./auth.sh)
