#!/usr/bin/env bash
pushd $(dirname $0)
docker-compose pull
docker-compose build
docker-compose up -d postgres
until pg_isready --host "$(docker-machine ip $DOCKER_MACHINE_NAME)"; do sleep 1; done
docker run --rm -ti --link $(basename $PWD)_postgres_1:postgres $(basename $PWD)_keystone keystone-manage db_sync
docker-compose up -d
until nc -vz "$(docker-machine ip $DOCKER_MACHINE_NAME)" 35357; do sleep 1; done
source <(../auth.sh keystone)
bash initial.sh
source <(../auth.sh)
popd
